# Используем официальный образ .NET SDK 9.0 для сборки и запуска
FROM mcr.microsoft.com/dotnet/sdk:9.0
# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app
# Копируем все файлы
COPY . .
# Переходим в папку backend внутри контейнера
WORKDIR /app/backend
# Восстанавливаем NuGet пакеты и зависимости
RUN dotnet restore
# Собираем приложение
RUN dotnet build
# Открываем порт 5207 для доступа к API
EXPOSE 5207
# Указываем на каком порту должно слушать приложение
ENV ASPNETCORE_URLS=http://*:5207
# Команда для запуска приложения
CMD ["dotnet", "run"]
